### ISSUE TITLE
Suggestion for updates to the warning descriptions

### ISSUE THREAD

**Issue by mdecandia** [dwavesystems/dwave-inspector#52]
Currently, the Chain Break Warning reads "a chain is broken in the lowest energy samples found", and the User Warning reads "all samples had broken chains"

This is to propose that we change them to "Lowest-energy samples contain a broken chain" (credits: Joel P.)
and
"All samples **have** broken chains" changing it to the present tense to match the other warnings.

<img width="2557" alt="Screen Shot 2020-02-06 at 15 46 54 PM" src="https://user-images.githubusercontent.com/7495207/73989544-f94fc580-48fa-11ea-8a77-697bbd94b6a5.png">

**Comment by randomir** [comment]
Both of these should now be fixed in master on `dwave-system` (fixes are in [`263c3c`](https://github.com/dwavesystems/dwave-system/commit/263c3cf0f0053ade092c4b72c22d4201148f7ec6) and [`970f3f`](https://github.com/dwavesystems/dwave-system/commit/970f3fd6c544ad889191b0f843600956470f67a4)).

@mdecandia, feel free to close this issue after you verify the fix.

**Comment by mdecandia** [comment]
will do. Thanks @randomir

**Comment by randomir** [comment]
@mdecandia, can we close this?

**Comment by mdecandia** [comment]
@randomir, yes. Closing ticket. Thanks
